apiVersion: v1
kind: Service
metadata:
  name: platform-canary
  annotations:
    metallb.io/address-pool: home-pool
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: platform-canary
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
